version: '3.8'

services:
  cryptpad:
    image: cryptpad/cryptpad:latest
    container_name: cryptpad
    restart: unless-stopped
    ports:
      - "8300:3000"
    environment:
      - CPAD_MAIN_DOMAIN=http://chadig-02.staging.chattanooga.digital:8300
      - CPAD_CONF_UNSAFE_ORIGIN=http://chadig-02.staging.chattanooga.digital:8300
    volumes:
      - cryptpad_config_fresh:/cryptpad/config
      - cryptpad_data_fresh:/cryptpad/data

volumes:
  cryptpad_config_fresh:
  cryptpad_data_fresh:
